# Generated by Django 4.2.5 on 2023-09-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("khanto_adds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="preco_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
